name: Sample C CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update apt cache
      run: sudo apt-get update

    - name: Set up C environment
      run: sudo apt-get install -y build-essential

    - name: Compile C program
      run: gcc sample.c -o sample
    
    - name: Run C program
      run: ./sample